name: Build web & publish to Github Pages

on:
  workflow_dispatch:

jobs:
  build-and-deploy-web:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Cache Flutter
        uses: actions/cache@v3
        id: flutter-cache
        with:
          key: $GITHUB_SHA-flutter
          path: ~/.flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
      # - name: Build and deploy to GH pages
      #   uses: bluefireteam/flutter-gh-pages@v7
      - run: flutter pub get
      - run: flutter build web --release
      - name: Deploy to GH pages
        uses: peaceiris/actions-gh-pages@v4