name: build-android

on:
  workflow_dispatch:

jobs:
  build-android-apk:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Cache Flutter
        uses: actions/cache@v3
        id: flutter-cache
        with:
          key: $GITHUB_SHA-flutter
          path: ~/.flutter

      - name: Cache Gradle
        uses: actions/cache@v3
        id: gradle-cache
        with:
          key: $GITHUB_SHA-gradle
          path: ~/.gradle

      - name: Set up JDK 19
        uses: actions/setup-java@v4
        with:
          java-version: "19"
          distribution: 'temurin'
          cache: "gradle"

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - run: flutter pub get

      - run: flutter build apk